---
name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy rustfmt

      - run: cargo binstall -y bpf-linker
      - name: Linting
        run: |
          cargo clippy -p caracal-ebpf  -- -D warnings
          cargo clippy --workspace --all-features --exclude caracal-ebpf  -- -D warnings
          cargo fmt --all -- --check

      - name: Build Caracal
        run: |
          just build-ebpf
          cargo build --release