---
name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy rustfmt

      - run: cargo binstall -y bpf-linker
      - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Caracal
        run: |
          just build-ebpf
          cargo build --release

      - name: Linting
        run: |
          cargo fmt --all -- --check
          cargo clippy -p caracal-ebpf  -- -D warnings
          cargo clippy --workspace --all-features --exclude caracal-ebpf  -- -D warnings
          
